DELETE FROM RATING;
INSERT INTO RATING  (RATING_NAME)  VALUES ( 'G') ; --1
INSERT INTO RATING (RATING_NAME) VALUES ( 'PG'); --2
INSERT INTO RATING (RATING_NAME) VALUES ( 'PG-13'); --3
INSERT INTO RATING (RATING_NAME) VALUES ( 'R'); --4
INSERT INTO RATING (RATING_NAME) VALUES ( 'NC-17'); --5
DELETE FROM GENRE;
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Комедия'); --1
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Драма'); --2
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Мультфильм'); --3
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Триллер'); --4
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Документальный'); --5
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Боевик'); --6
--INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('test@test.ru', 'test', 'testName', CAST('1986-12-01' as date));
--INSERT INTO FILM (FIlM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
--VALUES ('film', 'descr',  CAST('2002-06-15' as date), 90, 3);
