--DELETE FROM RATING;
INSERT INTO RATING  (RATING_NAME)  VALUES ( 'G') ; --1
INSERT INTO RATING (RATING_NAME) VALUES ( 'PG'); --2
INSERT INTO RATING (RATING_NAME) VALUES ( 'PG-13'); --3
INSERT INTO RATING (RATING_NAME) VALUES ( 'R'); --4
INSERT INTO RATING (RATING_NAME) VALUES ( 'NC-17'); --5
--DELETE FROM GENRE;
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Комедия'); --1
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Драма'); --2
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Мультфильм'); --3
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Триллер'); --4
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Документальный'); --5
INSERT INTO GENRE (GENRE_NAME) VALUES ( 'Боевик'); --6

